apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      environment: dev

# Sobrescribe dinámicamente las etiquetas de imagen para el entorno de desarrollo
images:
  - name: harbor.local:30002/gitops/frontend
    newTag: dev
  - name: harbor.local:30002/gitops/backend
    newTag: dev

patches:
  - path: patches/backend-config.yaml
