apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      environment: prod

# Sobrescribe dinámicamente las etiquetas de imagen para producción
images:
  - name: harbor.local:30002/gitops/frontend
    newTag: prod
  - name: harbor.local:30002/gitops/backend
    newTag: prod

patches:
  - path: patches/backend-prod.yaml
  - path: patches/frontend-prod.yaml
  - path: patches/backend-config.yaml
