apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson

# NOTA: Puedes generar este secret automáticamente con el comando:
# kubectl create secret docker-registry harbor-registry-secret \
#   --docker-server=harbor.local:30002 \
#   --docker-username=admin \
#   --docker-password='HarborAdmin123!' \
#   --docker-email=admin@example.com \
#   --namespace=default
#

data:
  # Base64 de {"auths":{"harbor.local:30002":{"username":"admin","password":"HarborAdmin123!","auth":"YWRtaW46SGFyYm9yQWRtaW4xMjMh"}}}
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IubG9jYWw6MzAwMDIiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiSGFyYm9yQWRtaW4xMjMhIiwiYXV0aCI6IllXUnRhVTRmTUdGeVltOXlRV1J0YVc1eE1qTWgiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIn19fQ==

